D0014: API finale.
SFTtech/openage-blog pull request #23
Opened 2019-05-31 04:08 UTC by heinezen

2019-05-31 08:47 UTC, simonsan approved these changes
Really nice work! 👍

2019-05-31 11:27 UTC, TheJJ requested changes
awesome!

2019-05-31 11:27 UTC, TheJJ commented on content/blog/landing_page.md
> +14. [Diplomatic Stances]({filename}/blog/D0014-openage_mod_api_finale.md)
copypasta error

2019-05-31 11:27 UTC, TheJJ commented on content/blog/D0014-openage_mod_api_finale_0.1.md
> +* **The first API draft:**
i was confused about this at first, maybe it helps to write something like "our first API draft attempt (September 2008)" :grin:

the *first* api draft sounds like something we've done recently or is the result.

2019-05-31 11:27 UTC, TheJJ commented on content/blog/D0014-openage_mod_api_finale_0.1.md
> +![modding API tree v0.1a]({static}/images/D0014-API-tree-0.1.svg)
i think we should add something like "we present you the result of hours of thought and discussions:" as a introduction to this image.

2019-06-26 19:46 UTC, TheJJ approved these changes

2019-06-26 19:47 UTC, merged